# Decompiled from: fs_image/cactuscon/ui/sprites.py
# This is a best-effort reconstruction from MicroPython bytecode.
# Some complex logic may be approximate or incomplete.

uos = uos
lv = lvgl
time = time
framebuf = framebuf
math = math
os = os
gc = gc
Logger = Logger
load_rgb565_file = load_rgb565_file
load_rgb565_single_frame = load_rgb565_single_frame
config = config
logger = Logger(config.LOG_LEVEL)
_SPRITE_CACHE = {}
_touch_cache_entry = <func_0>
get_cached_sprite = <func_1>
put_cached_sprite = <func_2>
_PRELOADED_PATHS = set()
MAX_UNPROTECTED_CACHE_ENTRIES = 4
MAX_UNPROTECTED_CACHE_BYTES = 204800
_count_unprotected_cache = <func_3>
_evict_oldest_unprotected = <func_4>
evict_sprite_cache = (None, None, 20, True)
STATION_CHARACTER_IDS = ['enigmox', 'hackachu', 'voltreign', 'cinderserp', 'runewing']
_PROTECTED_PATHS = set()
_CURRENT_PLAYER_GENUS = None
get_evolution_tree_sprite_paths = <func_6>
get_station_sprite_paths = <func_7>
_update_protected_paths = (None)
preload_essential_sprites = (None, None)
switch_player_creature_cache = <func_10>
CHARACTER_SPRITE_PATHS = ['/assets/images/sprites/hacktarchu.rgb565', '/assets/images/sprites/hackachu.rgb565', '/assets/images/sprites/hackachimon.rgb565', '/assets/images/sprites/voltiny.rgb565', '/assets/images/sprites/voltqueen.rgb565', '/assets/images/sprites/voltreign.rgb565', '/assets/images/sprites/cinderlet.rgb565', '/assets/images/sprites/cinderserp.rgb565', '/assets/images/sprites/cindervipe.rgb565', '/assets/images/sprites/blipbat.rgb565', '/assets/images/sprites/glyphbat.rgb565', '/assets/images/sprites/runewing.rgb565', '/assets/images/sprites/cipherkit.rgb565', '/assets/images/sprites/enigmox.rgb565', '/assets/images/sprites/cryptilox.rgb565']
preload_character_sprites = (None)
LVGLImage = __build_class__(<func_12>, 'LVGLImage')
LVGLSpriteActor = __build_class__(<func_13>, 'LVGLSpriteActor')
Sprite = __build_class__(<func_14>, 'Sprite')
SpriteActor = __build_class__(<func_15>, 'SpriteActor')
1 = 0
return 1
1 = 0
return 'buf'
2 = _PRELOADED_PATHS
3 = len(1)
4 = _count_unprotected_cache()
5 = 2
6 = _evict_oldest_unprotected()
5 = 6
4 = 1
0 = 0
1 = 0
2 = _SPRITE_CACHE
3 = ?
0 = 1
1 = 0
return (0, 1)
0 = None
1 = None
2 = _SPRITE_CACHE
3 = ?
4 = 0
1 = 4
0 = 2
5 = 0
return 5
return 0
19 = 0([])
4 = sum(<func_0>(_SPRITE_CACHE), 0)
5 = 4
6 = gc
7 = 100
return 'free_percent'
8 = time
9 = 0
10 = 0
11 = 2(_SPRITE_CACHE)
12 = 11
13 = <func_2>
14 = 'key'
10 = 14
9 = 1
12 = list(_SPRITE_CACHE)
15 = _touch_cache_entry(12)
14 = 0
10 = 14
9 = 1
return 'free_percent'
1 = 0
2 = 1
3 = []
return (3, 'size', 0)
return 1
1 = get_evolution_tree
2 = 1(0)
3 = []
4 = 2
5 = 'sprite_path'
return 3
0 = get_character
1 = []
2 = STATION_CHARACTER_IDS
3 = 0(2)
return 1
_PROTECTED_PATHS = set()
1 = get_station_sprite_paths()
1 = get_evolution_tree_sprite_paths(0)
2 = get_achievement_icon_paths
1 = 2()
2 = time
3 = get_genus_for_character
4 = 2
_CURRENT_PLAYER_GENUS = 3(0)
5 = list(_PROTECTED_PATHS)
6 = 0
7 = 0
8 = 0
9 = len(5)
10 = enumerate(5)
11 = 9
6 = 1
12 = load_rgb565_file(11)
6 = 1
8 = len(12)
7 = 1
13 = Exception
7 = 1
13 = None
14 = 4
return 'total_time_ms'
1 = get_genus_for_character
2 = 1(0)
return 'same_tree'
3 = set()
4 = EVOLUTION_TREE_INDEX
5 = []
6 = 5
7 = set(get_station_sprite_paths())
8 = 0
9 = 3
8 = 1
_CURRENT_PLAYER_GENUS = 2
10 = get_evolution_tree_sprite_paths(0)
11 = 0
9 = 10
12 = load_rgb565_file(9)
11 = 1
13 = Exception
13 = None
return 'same_tree'
return ?(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, logger, '[SPRITE_CACHE] preload_character_sprites is deprecated, use preload_essential_sprites', preload_essential_sprites, 'player_char_id', None, 'progress_callback', 0)
__init__ = (None, None, None, None, lv.COLOR_FORMAT.RGB565)
_infer_frame_dims = <func_1>
_auto_detect_static_dims = <func_2>
_load_sheet = (None)
get_frame_buffer = (None)
get_lvgl_src = (None)
next_frame = <func_6>
set_frame = <func_7>
reset = <func_8>
0.path = 1
0.color_format = 6
0.current_frame = 0
7 = get_cached_sprite(1)
8 = len(7)
9 = 1
8 = 6
10 = 2
11 = 10
4 = None
5 = 1
12 = 11
13 = 0
0.frame_width = 13
0.frame_height = 12
0.frame_width = 2
0.frame_height = 3
0.frames_per_row = 1
0.num_frames = 1
0.frames_per_col = 1
0.sheet_width = 0.frame_width
0.sheet_height = 0.frame_height
14 = 10
12 = 11
13 = 0
0.frame_width = 12
0.sheet_width = None
0.frame_height = 13
0.sheet_height = 13
14 = 10
2 = 1
3 = 5
0.frame_width = 2
0.frame_height = 3
0.frames_per_row = 4
15 = 3
0.num_frames = 1
0.num_frames = 5
0.frames_per_col = 0.frames_per_row
0.sheet_width = 4
0.sheet_height = 0.frames_per_col
14 = 10
0._from_cache = None
return (None, None)
4 = 2
5 = 4
return (None, None)
6 = 5
7 = math(6)
return (7, 7)
8 = [128, 96, 80, 72, 64]
9 = None
10 = None
11 = 8
12 = 11
13 = min(11, 12)
9 = (11, 12)
10 = 13
return 9
return (None, None)
2 = math(1)
return (2, 2)
3 = [320, 256, 240, 128, 64]
return (1, 3)
return (None, None)
0.sheet_buf = 1
0.sheet_buf = load_rgb565_single_frame(0.path, 0.frame_width, 0.frame_height)
0.sheet_buf = load_rgb565_file(0.path)
1 = 0.current_frame
1 = 0.num_frames
2 = 0.frames_per_row
3 = 0.frames_per_row
4 = 2
5 = 0.frame_height
6 = 2
7 = 0.frame_height(2)
8 = 0
9 = 4
10 = 2
return 7
2 = 1
3 = 'data'
return 3
0.current_frame = 0.num_frames
0.current_frame = 0.num_frames
0.current_frame = 0
__init__ = (0, 0)
add_action = <func_1>
set_action = (True)
_get_cached_frame_dsc = <func_3>
_update_display = <func_4>
_create_fallback_display = <func_5>
update = (None)
move_to = <func_7>
set_frame_delay = <func_8>
show = <func_9>
hide = <func_10>
destroy = <func_11>
0.parent = 1
0.x = 2
0.y = 3
0.visible = False
0.actions = {}
0.current_action = None
0.animation_frame_delay = 100
0.last_frame_update = 0
0.img_obj = None
0._current_img_dsc = None
0._frame_dsc_cache = {}
0._is_fallback = False
3 = 0
0.current_action = 1
0.current_action = 1
3 = (1, 2)
return 3
4 = 1
5 = 2
6 = 'data'
return 6
7 = Exception
7 = None
1 = 0.current_action
0.img_obj = 0.parent
2 = 1.current_frame
0._current_img_dsc = 2
3 = Exception
3 = None
0._is_fallback = True
0.img_obj = None
2 = 0.parent
0.img_obj = 2
1 = time
2 = 0.current_action
0.last_frame_update = 1
3 = 0.y
4 = 0.x
0.x = 1
0.y = 2
0.animation_frame_delay = 1
0.visible = True
0.visible = False
0.visible = False
0.current_action = None
0._current_img_dsc = None
0.img_obj = None
0._is_fallback = False
__init__ = (None, framebuf.RGB565)
_load_sheet = <func_1>
get_frame_buffer = <func_2>
draw = <func_3>
next_frame = <func_4>
set_frame = <func_5>
reset = <func_6>
0.frame_width = 2
0.frame_height = 3
0.num_frames = 4
0.color_format = 6
0.current_frame = 0
0.path = 1
0.frame_size = 2
0.frames_per_row = 4
0.frames_per_row = 5
0.frames_per_col = 0.frames_per_row
0.sheet_width = 0.frames_per_row
0.sheet_height = 0.frames_per_col
7 = 1
8 = 6
9 = 2
1 = 2
0.sheet_buf = bytearray(1)
2 = open(0.path, 'rb')
0.sheet_fb = 0.color_format
1 = bytearray(0.frame_size)
2 = 0.color_format
3 = 0.frames_per_row
4 = 0.frames_per_row
5 = 0.frame_width
6 = 0.frame_height
return 1
4 = 0
0.current_frame = 0.num_frames
0.current_frame = 0.num_frames
0.current_frame = 0
__init__ = (0, 0)
add_action = <func_1>
set_action = <func_2>
update = <func_3>
draw = <func_4>
move_to = <func_5>
hide = <func_6>
show = <func_7>
0.display = 1
0.x = 2
0.y = 3
0.actions = {}
0.current_action = None
0.visible = False
0.current_action = 1
0.current_action = 1
1 = 0.current_action
0.x = 1
0.y = 2
0.visible = False
0.visible = True