# Decompiled from: fs_image/cactuscon/ui/panels/character_evo.py
# This is a best-effort reconstruction from MicroPython bytecode.
# Some complex logic may be approximate or incomplete.

lv = lvgl
time = time
BasePanel = BasePanel
Logger = Logger
config = config
XP_BASE_LEVEL = XP_BASE_LEVEL
EVOLVE_REQUIRED_LEVEL = EVOLVE_REQUIRED_LEVEL
FORM_STAGE_NAMES = FORM_STAGE_NAMES
get_character = get_character
get_evolution_tree = get_evolution_tree
get_current_form_index = get_current_form_index
set_current_form_index = set_current_form_index
get_player_pack = get_player_pack
get_total_xp_for_level = get_total_xp_for_level
get_xp_for_level = get_xp_for_level
get_creature_stats = get_creature_stats
can_evolve = can_evolve
get_move = get_move
prefs = prefs
logger = Logger(config.LOG_LEVEL)
CharacterEvoPanel = __build_class__(<func_0>, 'CharacterEvoPanel', BasePanel)
__init__ = 0
create_ui = <func_1>
on_show = <func_2>
update = <func_3>
_load_character_data = <func_4>
_refresh_panel = <func_5>
_get_evo_state = <func_6>
_get_form_image_descriptor = <func_7>
_set_image_tint = <func_8>
_fit_form_image = <func_9>
_set_enabled = <func_10>
_show_modal = <func_11>
_close_modal = (None)
_on_form_tapped = <func_13>
_on_evolve_clicked = <func_14>
return 0
1.character_id = getattr(config, 'PLAYER_CHARACTER_ID', 'deeno')
1.character_name = 'Unknown'
1.level = 1
1.xp_total = 0
1.xp_into_level = 0
1.xp_needed = XP_BASE_LEVEL
1._evo_image_cache = {}
1._default_tint = 6710886
1._deferred_forms = []
1._deferred_current_form_idx = 0
1._forms_loaded = False
1 = 0.screen
2 = 26
3 = 0.screen
4 = 3
5 = 3
6 = 0.screen
7 = []
8 = 0
9 = 6
10 = 9
11 = 9
12 = 0
13 = 0.screen
14 = 13
15 = 30
0._deferred_forms = 0
0._deferred_current_form_idx = 'Loading evolution data...'
0._forms_loaded = False
1 = enumerate(0._deferred_forms)
2 = 0._forms_loaded
3 = 'id'
4 = 1
0._forms_loaded = True
1 = get_player_pack(prefs)
2 = 'active_character'
2 = getattr(config, 'PLAYER_CHARACTER_ID', None)
3 = get_creature_stats(prefs, 2)
4 = 'level'
5 = 'xp'
0.character_id = 2
0.level = 4
0.xp_total = 5
0.xp_needed = get_xp_for_level(4)
6 = get_total_xp_for_level(4)
0.xp_into_level = 0(5, 6)
0.character_name = 'Unknown'
0._evo_image_cache = {}
1 = 0
2 = ?
3 = 'level'
4 = 'xp'
5 = []
6 = enumerate(5)
7 = 'form_slots'
8 = 'btn'
9 = 'img'
10 = 'label'
11 = None
12 = 1
13 = None
14 = 'id'
15 = 14
1 = get_evolution_tree(0.character_id)
2 = get_current_form_index(prefs, 0.character_id)
2 = 0(len(1), 1)
return (1, 2)
2 = 'id'
3 = 2
return 'dsc'
4 = 'sprite_path'
5 = {}
6 = 48
7 = 6
8 = 2
9 = 0._evo_image_cache
return 7
4 = Exception
4 = None
3 = Exception
3 = None
3 = Exception
3 = None
3 = 'modal'
3 = 0.screen
4 = 3
5 = 4
6 = 4
7 = 24
2 = 'modal'
2 = 0
3 = ?
4 = 1
5 = []
6 = []
7 = get_move(6)
8 = ['strengths', 'Weaknesses: {}', 4, 'weaknesses']
2 = 0
3 = ?
4 = 1
5 = None
6 = 'id'
7 = can_evolve(prefs, 0.character_id)
0.game_ui.pending_evolution = 'old_id'